"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const KEY = "canvas-ratio:weekly-review:v1";
const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const monthValue = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
function getMonthStory(date: Date) { const values: string[] = []; const end = new Date(date.getFullYear(), date.getMonth() + 1, 0); for (let day = 1; day <= end.getDate(); day += 1) { const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; try { const data = JSON.parse(localStorage.getItem(`${KEY}:${key}`) ?? "{}"); Object.values(data).forEach(value => { if (typeof value === "string" && value.trim()) values.push(value); }); } catch {} } return values.join("\n"); }

export function MonthlyReviewPage() {
  const [offset, setOffset] = useState(0); const [content, setContent] = useState(""); const [from, setFrom] = useState(monthValue(new Date())); const [to, setTo] = useState(monthValue(new Date())); const [notice, setNotice] = useState(""); const [ready, setReady] = useState(false);
  const month = useMemo(() => { const date = new Date(); date.setDate(1); date.setMonth(date.getMonth() + offset); return date; }, [offset]);
  useEffect(() => { const key = `canvas-ratio:monthly-review:v1:${monthValue(month)}`; const saved = localStorage.getItem(key); setContent(saved ?? getMonthStory(month)); setReady(true); setNotice(""); }, [month]);
  useEffect(() => { if (ready) localStorage.setItem(`canvas-ratio:monthly-review:v1:${monthValue(month)}`, content); }, [ready, content, month]);
  function save() { localStorage.setItem(`canvas-ratio:monthly-review:v1:${monthValue(month)}`, content); setNotice("Monthly review saved."); }
  async function copyReview() { if (from > to) { setNotice("Start month must be before end month."); return; } const output: Record<string, string> = {}; const [sy, sm] = from.split("-").map(Number); const [ey, em] = to.split("-").map(Number); const cursor = new Date(sy, sm - 1, 1); const end = new Date(ey, em - 1, 1); while (cursor <= end) { const key = monthValue(cursor); output[key] = localStorage.getItem(`canvas-ratio:monthly-review:v1:${key}`) ?? getMonthStory(cursor); cursor.setMonth(cursor.getMonth() + 1); } const text = `${JSON.stringify(output, null, 2)}\n\nSummarize this JSON into exactly 1 professional LinkedIn/CV bullet point. Make it achievement-oriented, concise, and start with an action verb.`; try { await navigator.clipboard.writeText(text); } catch { const area = document.createElement("textarea"); area.value = text; document.body.appendChild(area); area.select(); document.execCommand("copy"); area.remove(); } setNotice("Review copied."); }
  return <main className="min-h-screen bg-[#F7F8F3] px-4 py-6 text-[#181818] sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b-2 border-[#1A1A1A] pb-5"><div><Link href="/" className="border-2 border-[#1A1A1A] bg-[#1A1A1A] px-3 py-2 text-sm font-black text-white">Home</Link><h1 className="mt-5 text-4xl font-black">Monthly Review</h1><p className="mt-2 font-black">{MONTHS[month.getMonth()]} {month.getFullYear()}</p></div><div className="flex items-center gap-2"><button onClick={() => setOffset(value => value - 1)} className="border-2 border-[#1A1A1A] bg-white px-4 py-2 text-xl font-black">←</button><button onClick={() => setOffset(value => value + 1)} className="border-2 border-[#1A1A1A] bg-white px-4 py-2 text-xl font-black">→</button><button type="button" onClick={copyReview} className="border-2 border-[#1A1A1A] bg-[#22D3EE] px-4 py-2 font-black">Copy Review</button></div></header>{notice && <p className="mt-4 font-black">{notice}</p>}<section className="mt-6 flex flex-wrap gap-4 border-2 border-[#1A1A1A] bg-white p-4"><label className="font-black">From month<input type="month" value={from} onChange={event => setFrom(event.target.value)} className="ml-2 border-2 border-[#1A1A1A] p-2" /></label><label className="font-black">To month<input type="month" value={to} onChange={event => setTo(event.target.value)} className="ml-2 border-2 border-[#1A1A1A] p-2" /></label></section><section className="mt-5 border-2 border-[#1A1A1A] bg-white p-5 shadow-[4px_4px_0_#1A1A1A]"><h2 className="text-2xl font-black">{MONTHS[month.getMonth()]} {month.getFullYear()}</h2><textarea value={content} onChange={event => setContent(event.target.value)} rows={18} className="mt-4 w-full resize-y border-2 border-[#1A1A1A] p-4 font-bold" placeholder="Monthly rollup from Weekly Review..." /><button type="button" onClick={save} className="mt-3 border-2 border-[#1A1A1A] bg-[#FFD91A] px-5 py-2 font-black shadow-[3px_3px_0_#1A1A1A]">Save</button></section></div></main>;
}
